### ISSUE TITLE
Move documentation off of readthedocs

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/Documentation#101]
Continuation of #95 

Essentially you'll want to set up a webhook for whenever master is pushed to. This will then send out a notification, which a program like https://github.com/OllieJones/git-webhook-responder/blob/master/README.md can respond to and run a command, like `mkdocs build`, on.

It's not too difficult to set up and self-host. We'll also need to provide a redirect from the existing documentation URLs to the new ones. My suggestion is just replacing each page with some text that says "The documentation has moved to docs.zeronet.io. You will be redirected in 5 seconds, otherwise click [here]()".

And then we have some JS that will take them to the exact docs page they wanted to go to, but now on the new domain.

I'm fine with writing the JS and getting that working if you're ok with doing the hosting part @HelloZeroNet?

**Comment by HelloZeroNet** [comment]
Yeah I will setup the hosting. I think we should do the redirect part in js, so we don't need to replace every page.

**Comment by anoadragon453** [comment]
Yeah that sounds good. I'll see what I can do.

**Comment by HelloZeroNet** [comment]
First try: https://zeronet.io/docs/
Looks like the menu order is got fixed

**Comment by anoadragon453** [comment]
Wonderful! Have you set up the webhooks yet? Also do you want to try to `mkdocs-material` theme yet?

**Comment by HelloZeroNet** [comment]
Sounds good for me, tomrrow I will setup the mkdocs-material theme

**Comment by HelloZeroNet** [comment]
have added the webhooks + allowed cors, but seems like github does not really works well today, problem with PR mergning and webhooks does not seems to trigger

Looks like there is some problem with images: https://zeronet.io/docs/using_zeronet/sample_sites/

**Comment by DaniellMesquita** [comment]
@HelloZeroNet 
Could you create subdomain https://awesome.zeronet.io/ and point it to GitHub pages?
I'm creating awesome list for ZeroNet

**Comment by anoadragon453** [comment]
@HelloZeroNet Yeah it's [broken](https://status.github.com) for everyone.

Regarding the images, they seem to be linking to https://zeronet.io/img/zerotalk.png instead of https://zeronet.io/docs/img/zerotalk.png. I imagine this is the problem. I suppose this is the issue of using https://zeronet.io/docs/... instead of https://docs.zeronet.io/

We could either change the documentation (which would require everyone rehosting to start their URLs with `/docs/`), or you could put in a URL rewrite rule into nginx like so:

```
// Inside your server {} block...
location /docs/ {
    rewrite ^/img/(.*)$ /docs/img/$1 last;
}
```

**Comment by HelloZeroNet** [comment]
Fixed the images by using relative pats

**Comment by anoadragon453** [comment]
I think we can safely close this one now :)
