### ISSUE TITLE
How does Zeronet work with Tor?

### ISSUE THREAD

**Issue by Mikaela** [HelloZeroNet/Documentation#147]
I am mainly wondering:

* What commands does Zeronet issue Tor controlport/controlsocket?
* Are the created hidden services / onions persistent or are they regenerated upon Zeronet restart or when?
  * Is it possible to have accidentally HiddenServiceSingleHopMode/HiddenServiceNonAnonymousMode onions?
    * What happens if those onions are given to anonymous hidden service again? (Tor itself is said to prevent this at least for the onions generated by it).

My two last questions are, because I started running multiple Tor instances on the sme host, one for single hop onions for faster SSH through NATs and one for normal client (as single hop onions require SocksPort 0). Only later I checked how to make the client be used by everything instead of the single hop onion and I wonder if the client is compromised by Zeronet even if it only hosts Zeronet services. My Zeronet instance itself is not compromised, because I am running it in both Tor and clearnet IPv6.

I think the two first questions could also interest other users in the FAQ or similar place.

**Comment by HelloZeroNet** [comment]
It's using `ADD_ONION NEW:RSA1024 port=X` command to create new onion services, that are generated on every startup, so it's not persistent.

It does not check the tor config values, so it's possible to enable "HiddenServiceSingleHopMode/HiddenServiceNonAnonymousMode" settings.


Right now it's not possible to set the hidden service addresses manually, so it will report the trackers and expect connection from the hidden services it generates on the startup. (using the ADD_ONION command)

I hope this answer you questions.

**Comment by Mikaela** [comment]
Thank you
