### ISSUE TITLE
Broken link in FAQ

### ISSUE THREAD

**Issue by twerq** [HelloZeroNet/Documentation#153]
Section How to make ZeroNet work with Tor under Linux/MacOS? [go](https://zeronet.readthedocs.io/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linuxmacos)

Install Tor for your OS following Tor's official guidelines: [Linux](https://www.torproject.org/download/download-unix.html.en) Mac.

Link to official guidelines for Linux gives 404 Not Found

**Comment by HelloZeroNet** [comment]
Thanks for reporting it's fixed now: https://zeronet.io/docs/faq/#how-to-make-zeronet-work-with-tor-under-linuxmacos

(the readthedocs link is outdated and no longer updating)
