### ISSUE TITLE
Instructions to use with Tor Browser in the FAQ are out of date

### ISSUE THREAD

**Issue by AFlowOfCode** [HelloZeroNet/Documentation#155]
New steps are:

* Start the Tor Browser
* Go to address about:config & accept risk warning
* search "no_proxies_on"
* double click the preference entry
* enter 127.0.0.1 & press OK

**Comment by HelloZeroNet** [comment]
Thanks, updated: https://github.com/HelloZeroNet/Documentation/commit/19f6e9bdada0994d0b8ec18606f8332b2d2de329
