### ISSUE TITLE
tor section is outdated 

### ISSUE THREAD

**Issue by icf20** [HelloZeroNet/Documentation#167]
How to use ZeroNet with the Tor browser?¶

In Tor mode it is recommended to use ZeroNet from within the Tor Browser:

    Start the Tor Browser
    Go to address about:preferences#advanced
    Click Settings...
    Enter 127.0.0.1 to field No proxy for
    Open http://127.0.0.1:43110 in the browser

If you still see a blank page: - Click on NoScript's button (first on the toolbar) - Choose "Temporary allow all this page" - Reload the page

what settings?

![image](https://user-images.githubusercontent.com/17784575/82561979-a67ddf00-9b74-11ea-955a-1b6939cc6780.png)

**Comment by HelloZeroNet** [comment]
Where do you see that description?

Here is the updated section:
https://zeronet.io/docs/faq/#how-to-use-zeronet-with-the-tor-browser

> How to use ZeroNet with the Tor browser?
> In Tor mode it is recommended to use ZeroNet from within the Tor Browser:
> Start the Tor Browser
> Go to address about:config & accept risk warning
> Search no_proxies_on
> Double click the preference entry
> Enter 127.0.0.1 & press OK
> Open http://127.0.0.1:43110 in the browser

**Comment by icf20** [comment]
> Where do you see that description?

in the link from the error from the home page message? http://127.0.0.1:43110/1DocsYf2tZVVMEMJFHiDsppmFicZCWkVv1/faq/#how-to-make-zeronet-work-with-tor-under-linux
