### ISSUE TITLE
FileList Missing from API Documentation

### ISSUE THREAD

**Issue by mishfit** [HelloZeroNet/Documentation#50]
Just noticed [this commit](https://github.com/HelloZeroNet/ZeroNet/commit/eee65da257e9620ab603527f98bbeb82e2641c1a)! It's actually quite powerful and could be used to eliminate the need for a database (when handling data files). I'm writing a small site to show you what I mean, but for now `fileList` should probably be added to the API

**Comment by HelloZeroNet** [comment]
Thanks for reporting, added: https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#filelist-inner_path
