### ISSUE TITLE
"signers_sign" and "signs" format in data/users/content.json

### ISSUE THREAD

**Issue by mishfit** [HelloZeroNet/Documentation#51]
In the documentation the "signers_sign" property in the `data/users/content.json` file states that the format of the signed string is `[signers_required]:[signer address],[signer address]`

Does that mean that one has to concat the text like so:
```
"signers_required:1LcsFJPGfirbL4x6zJ41tPJBxNQ87h9wuG,12bZndAwUbiuxENeKcXqt26ctQr81TvLBv"
```
_(addresses are just for an example)_

then sign it with the private keys associated with the addresses?

**Comment by mishfit** [comment]
I've also created a [gist](https://gist.github.com/mishfit/0ad0ce9f8a6e20763f0287985ea1d028) that appears to do this reliably

**Comment by HelloZeroNet** [comment]
signers_sign only in use for root content.json, for any other content.json files you should use the include part, eg.: https://github.com/HelloZeroNet/ZeroTalk/blob/master/content.json#L78-L83
