### ISSUE TITLE
Explain how to become a ZeroNet user cert authority

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/Documentation#55]
There lacks documentation on how to create your own ID provider. Explanation of user cert format and ZeroNet's interpretation of user certificate is needed.

**Comment by MuxZeroNet** [comment]
I seem to figure it out and I can write about it. Do you like it to be on a separate page or on the `content.json` format page?

**Comment by HelloZeroNet** [comment]
Sorry, i forgot about this.
Please create a separate page!

**Comment by MuxZeroNet** [comment]
https://zeronet.readthedocs.io/en/latest/site_development/cert_authority/

I think that's it. If you have any further questions, feel free to open a new issue.
