### ISSUE TITLE
How many bytes are sent at a time?

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/Documentation#70]
According to the documentation,
> max 512 bytes got sent in a request, so you need multiple requests for larger files.

However, there is an experimental option
> `--stream_downloads`  Stream download directly to files (experimental)

I would insist on using the former method, since it is easier to implement, and it allows portage to datagram sockets.

- - -
_Edit:_ Thanks for clarification. It turns out in streaming mode, the file data is appended after, not nested into, the response.
- - -

For example, in **datagram** programming, you write:
```python
data, address = sock.recvfrom(32*1024)
```

Then you hope one or more ZeroNet packets will fit into your 32k buffer.
```
 Buffer                (32k)
+---------------------------+
|###########################|   [ # ] - filled
|##################         |   [   ] - empty
|                           |
+---------------------------+
```

Make it a stream and parse it until exhausted:
```
stream = BytesIO(data)
```

If a packet is bigger than the buffer, then there is no way to fully receive the packet. It will be truncated, and the oversize part will be thrown away by the kernel.

**Comment by HelloZeroNet** [comment]
The difference between the two method:

Without streaming
```
> {"cmd": "getFile", "id": 1, "inner_path": "content.json", "size": 1234}
< {"cmd": "response", "to": 1, "content": "content of the file"}

With streaming
> {"cmd": "streamFile", "id": 1, "inner_path": "content.json", "size": 1234}
< {"cmd": "response", "to": 1, "stream_bytes": 1234}
< content of the file

This way we can avoid the msgpack parshing / encoding on large amount of data.
For file requests larger than 256kb the streaming is enabled even if the client not used with `--stream_downloads`.
Actually there is no real reason not enabling it by default. So I will use zeronet with it in the next days to see if there is any issue.

**Comment by MuxZeroNet** [comment]
Thanks. Please document this streaming mode.

**Comment by MuxZeroNet** [comment]
FYI, if you will implement **datagram** (including I2P datagram) **support** in the future, try to keep each packet under 10 KB. The hard limit is 32 KB, but that includes the size of metadata like I2P headers, SAM headers, etc.

> [**Datagram Length**](https://geti2p.net/en/docs/api/datagrams)
> The more message fragments, the more likely that one of them will be dropped by an intermediate hop. Messages larger than a few KB are not recommended. Over about 10 KB, the delivery probablility drops dramatically.
> 
> [**I2P datagrams can be up to several KB**](https://geti2p.net/en/get-involved/develop/applications)
> While the upper limit is nominally 32 KB, the message is fragmented for transport, thus dropping the reliability of the whole. Datagrams over about 10 KB are not currently recommended.
