### ISSUE TITLE
How to format JSON file before signing it?

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/Documentation#74]
What deterministic algorithms/formatting parameters are used to format a JSON file for signing?
- Identation method?
- Sort keys?
- Which keys are removed prior to signing?

**Comment by HelloZeroNet** [comment]
I have added specification on the dumped json format: https://zeronet.readthedocs.io/en/latest/site_development/content_json/#signs

Unfortunately I have not found any offical specification on standard Bitcoin message signature format, so I added the PR's link.

**Comment by MuxZeroNet** [comment]
Electrum is especially infamous for not following the conventions the rest of the crypto community agreed on. [It has a different serialization format,](https://github.com/MuxZeroNet/zerolib/blob/f13126e04bf99b1b416a7ea5b5cad7924cdc15a4/zerolib/integrity/bitcoin.py#L68-L93) and [adds a message-dependent magic header to the signed message.](https://github.com/vbuterin/pybitcointools/blob/87806f3c984e258a5f30814a089b5c29cbcf0952/bitcoin/main.py#L405) In the documentation, you may need to note this inconsistency.

**Comment by HelloZeroNet** [comment]
I have added some corrections, please feel free to edit it if you think it need some more changes:
https://zeronet.readthedocs.io/en/latest/site_development/content_json/#signs
