### ISSUE TITLE
"Edit on Github" link points to wrong repository?

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/Documentation#76]
Hello,

on the top right of the page https://zeronet.readthedocs.io/en/latest/ is "Edit on GitHub" but it points to:
https://github.com/HelloZeroNet/ZeroNet
instead of:
https://github.com/HelloZeroNet/Documentation

i found only one related file: /Documentation/readthedocs/breadcrumbs.html

if this is intended, i apologize, please close this

**Comment by HelloZeroNet** [comment]
Yeah, I also found this bug and tried to report to readthedocs, but it's still not fixed: https://github.com/rtfd/readthedocs.org/issues/1422

**Comment by grez911** [comment]
I reopened this issue https://github.com/rtfd/readthedocs.org/issues/3515

**Comment by HelloZeroNet** [comment]
Thanks for the investigation. I removed the custom theme + added a simple workaround for the bug as it seemed the easiest solution.

https://github.com/HelloZeroNet/Documentation/blob/master/docs/docs.js#L6-L15

The edit / view buttons should work fine now
