### ISSUE TITLE
ImportError: No module named mkdocs.cli

### ISSUE THREAD

**Issue by ivanhjc** [HelloZeroNet/Documentation#80]
I'm trying to launch the site after I fork and clone the project. When I run `py start.py` I get the error:

    Traceback (most recent call last):
       File "E:/Workspace/Intellij/Documentation/start.py", line 6, in <module>
         from mkdocs.cli import cli
    ImportError: No module named mkdocs.cli

So what is this [mkdocs.cli](https://github.com/HelloZeroNet/Documentation/blob/c4b499106a235a397cc0c06510de3fa9d825bfac/start.py#L6) thing? Is there something missing in the code? I'm running on Windows 7 and using both Python 2.7 and Python 3.5 and I've had mkdocs 0.17.3 installed.

**Comment by HelloZeroNet** [comment]
probably it was removed somewhere, try using mkdocs serve

**Comment by ivanhjc** [comment]
Launched successfully with `mkdocs serve`

**Comment by anoadragon453** [comment]
This issue can be closed.
